name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: |
          pnpm run type-check
          pnpm run lint
          pnpm run test
      
      - name: Build for production
        run: pnpm run build
        env:
          NODE_ENV: production
      
      - name: Generate standalone file
        run: |
          # Copy the built index.html as the standalone file
          cp dist/index.html bip39-standalone.html
          
          # Calculate SHA256 hash
          sha256sum bip39-standalone.html > bip39-standalone.html.sha256
          
          # Create release notes
          echo "## Release Notes" > release-notes.md
          echo "" >> release-notes.md
          echo "### Changes" >> release-notes.md
          echo "- Modern TypeScript and React implementation" >> release-notes.md
          echo "- Improved security and user experience" >> release-notes.md
          echo "- PWA support for offline usage" >> release-notes.md
          echo "- Comprehensive test coverage" >> release-notes.md
          echo "" >> release-notes.md
          echo "### Security" >> release-notes.md
          echo "- SHA256 hash: \`$(cat bip39-standalone.html.sha256 | cut -d' ' -f1)\`" >> release-notes.md
          echo "" >> release-notes.md
          echo "### Usage" >> release-notes.md
          echo "1. Download \`bip39-standalone.html\`" >> release-notes.md
          echo "2. Verify the SHA256 hash matches the one above" >> release-notes.md
          echo "3. Open the file in a web browser (preferably offline)" >> release-notes.md
          echo "" >> release-notes.md
          echo "🤖 Generated with modern web technologies" >> release-notes.md
          echo "" >> release-notes.md
          echo "Built from commit: \`${{ github.sha }}\`" >> release-notes.md
      
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: release-notes.md
          draft: false
          prerelease: false
      
      - name: Upload standalone HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bip39-standalone.html
          asset_name: bip39-standalone.html
          asset_content_type: text/html
      
      - name: Upload SHA256 hash
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bip39-standalone.html.sha256
          asset_name: bip39-standalone.html.sha256
          asset_content_type: text/plain
      
      - name: Upload source archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist
          asset_name: bip39-source-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip